### ISSUE TITLE
Does not support Steam Version of the game

### ISSUE THREAD

**Issue by TechnoJo4** [robot9706/FSSE#78] opened 2017-04-01 19:57 UTC
Mods, Open Save Folder, And "Setting > Discover", Don't work In the Steam Version Of The Game.

**Comment by ghost** [comment] 2017-04-01 20:29
You can manually put it in "\steam\steamapps\common\Fallout Shelter\" ; then it does recognize the json files just fine, and you can select the settings.

But the problem is that the game stays frozen on the loading screen because of the 'Assembly-CSharp.dll'.  (At least, this occurred when I tested it)

**Comment by robot9706** [comment] 2017-04-01 20:36
@TechnoJo4: Yes the Steam version is not supported, there's nothing new here. I'll add support sometime.
@Jaspervv: The mods aren't updated so it won't work. The update will be released tomorrow (hopefully).

**Comment by TechnoJo4** [comment] 2017-04-01 20:39
Thanks for the Info,
Just to tell you save location is "%appdata%\..\Local\FalloutShelter"

**Comment by robot9706** [comment] 2017-04-02 11:40
@Jaspervv: The mods are now updated both on Nexus and the FSSE site. They seem to be working fine, but I haven't tested them in much detail.

**Closed as completed** 2017-04-05 18:14 UTC
